spring:
  application:
    name: "configserver"
  profiles:
    # active: native (activate native profile only for classpath or file approach)
    active: git
  cloud:
    config:
      server:
        # native:
          # search-location: "classpath:/config"
          # search-location: "file:///Users//karanjain//config"
        git:
          uri: "https://github.com/karanjain88/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull : true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "mlwGYZtRUYnojW5LMb2kFJeyu3ADgOPirjKG0Z1VmDRJ1VcK4KIzJDEcvRd1bn7E"


server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"